name: Generate Manifest

on:
  push:
    paths:
      - 'cod4x-server/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate manifest
        run: |
          python update/generate_manifest.py

      - name: Commit and push manifest
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add update/manifest.json

          git diff --cached --quiet || git commit -m "Auto-update manifest"
          git push